CODE_ISSUE_ERROR = '인증번호가 이미 발급되었습니다.'
PHONE_VERIFICATION_ERROR = '전화번호 혹은 인증번호를 다시 확인해주세요.'
CODE_EXPIRED_ERROR = '인증번호가 만료되었습니다.'
PASSWORD_MISMATCH_ERROR = '비밀번호가 일치하지 않습니다.'
LOGIN_ERROR = '이메일 혹은 패스워드 오류입니다.'
ACCESS_ERROR = '접근 권한이 없습니다.'
EMAIL_NOT_FOUND_ERROR = '등록되지 않은 이메일입니다.'

REGISTER_SUCCESS = '회원가입이 완료되었습니다.'
LOGIN_SUCCESS = '로그인이 완료되었습니다.'
PASSWORD_CHANE_SUCCESS = '비밀번호 변경이 완료되었습니다.'
