# Generated by Django 4.0.3 on 2022-03-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneverification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='security_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='security code'),
        ),
    ]
